export interface Location {
  slug: string;            // URL slug (matches existing junkmd.com where possible)
  name: string;            // display name
  zips?: string[];
  neighborhoods?: string[];
  landmarks?: string[];
  highways?: string[];
  intro: string;
  localSections?: { heading: string; body: string }[];
  faqOverrides?: { q: string; a: string }[];
}

const SD_LANDMARKS = ["Balboa Park", "San Diego Zoo", "USS Midway", "Petco Park", "Mission Bay"];
const COASTAL_LANDMARKS = ["Sunset Cliffs", "La Jolla Cove", "Pacific Beach Pier", "Cabrillo National Monument"];

export const LOCATIONS: Location[] = [
  // ───── Existing 42 (rebuilt) ─────
  {
    slug: "junk-removal-san-diego",
    name: "San Diego",
    zips: ["92101", "92103", "92104", "92106"],
    neighborhoods: ["Downtown", "Gaslamp", "East Village", "Hillcrest", "Bankers Hill"],
    landmarks: SD_LANDMARKS,
    highways: ["I-5", "I-805", "CA-163"],
    intro: "This is home base. JunkMD+ covers the whole city — downtown high-rises and Gaslamp condos, the canyon neighborhoods, the older homes east of the 805, and everything out to the coast. Because we're local and central, we move fast across all of it, and most of our same-day work happens right here in the city. Whatever corner of San Diego you're in, there's a good chance we're already working nearby.",
    localSections: [
      { heading: "Every kind of property, one city", body: "San Diego runs the full range — downtown towers with loading docks and elevator rules, Gaslamp and East Village condos, hillside homes in the canyon neighborhoods, and established single-family houses across the older parts of town. We've cleared all of it, and we bring the right truck and crew for whichever one you're in. For downtown buildings, tell us about dock access or elevator reservations when you book and we'll handle the logistics ahead of time." },
      { heading: "Fast, central, and neighborhood-deep", body: "Being based in the city means we're usually minutes from your job, not crossing the county to get there — which is why so much of our same-day work is right here. We also run dedicated pages for individual San Diego neighborhoods, so if you're in a specific area like Hillcrest, North Park, or Point Loma, you'll find local detail there too. Whatever you've got, you get a flat quote up front and a swept space when we leave." },
    ],
    faqOverrides: [
      { q: "Do you cover all of San Diego?", a: "Yes — the whole city is our home base, from downtown and the urban core to the canyon neighborhoods and out to the coast. Most of our same-day work happens right here." },
      { q: "Can you handle a downtown high-rise or condo with a loading dock?", a: "Yes, regularly. Tell us about dock access, elevator reservations, or any building COI requirements when you book and we'll have the logistics sorted before we arrive." },
      { q: "How fast can you come out in San Diego?", a: "Often same day, since we're central and usually working nearby. Text photos of what needs to go for a quick quote and we'll get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-la-jolla",
    name: "La Jolla",
    zips: ["92037"],
    neighborhoods: ["La Jolla Village", "La Jolla Shores", "Bird Rock", "Mount Soledad", "Windansea"],
    landmarks: ["La Jolla Cove", "Scripps Pier", "Torrey Pines"],
    highways: ["I-5", "La Jolla Village Dr"],
    intro: "La Jolla jobs run an unusual range — oceanfront estates above Windansea, mid-century homes on Mount Soledad, condos packed into The Village. We've hauled here long enough to know the quirks: narrow streets, short steep driveways, and a lot of work sitting behind HOA gates or in buildings with freight-elevator rules. We plan for that before the truck shows up.",
    localSections: [
      {
        heading: "Getting a truck into La Jolla",
        body: "Coastal La Jolla isn't built for big trucks. Around The Village and the Shores, parking is tight and time-limited, so we scout the approach and bring the right-size vehicle rather than block a lane for an hour. On the hillside lots near Mount Soledad and Bird Rock, the challenge is driveway grade and carry distance — we'd rather send a third crew member than risk a scrape on a tight turn. In a gated community or a condo tower, tell us the gate code and elevator situation when you book and we'll handle the building's COI or reservation paperwork ahead of time.",
      },
      {
        heading: "The work we do most here",
        body: "A lot of our La Jolla jobs come through realtors and property managers prepping a home for sale, and from families clearing an estate. Both deserve a careful hand: we set keepsakes aside, document before-and-after, and donate what still has life through Goodwill and the Salvation Army rather than defaulting to the landfill. Whether it's one oceanview condo's worth of old furniture or a full multi-level estate, you get a flat quote up front and a crew that leaves the place swept.",
      },
    ],
    faqOverrides: [
      { q: "Can you handle pickups in gated La Jolla communities and condo buildings?", a: "Yes, regularly. Share the gate code, building access rules, and any elevator or COI requirements when you book, and we'll have the paperwork sorted before we arrive." },
      { q: "Do you charge extra for the tight streets and steep driveways?", a: "No surprise surcharges. Pricing is volume-based — what you pay depends on how much we haul, not how tricky the access is. You approve the flat quote before we start." },
      { q: "I'm a realtor on a tight listing timeline — how fast can you come?", a: "Often same or next day. A big share of our La Jolla work is listing prep and estate clear-outs on deadline. Text photos for a quick quote and we'll usually get you a 2-hour arrival window fast." },
      { q: "What happens to items removed from a La Jolla home?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture and household goods that are easy to rehome." },
    ],
  },
  {
    slug: "junk-removal-pacific-beach",
    name: "Pacific Beach",
    zips: ["92109"],
    neighborhoods: ["North PB", "Crown Point", "Mission Beach", "Sail Bay"],
    landmarks: ["PB Pier", "Crystal Pier", "Mission Bay"],
    highways: ["I-5", "Mission Bay Dr"],
    intro: "Pacific Beach runs on turnover — vacation rentals flipping between guests, students moving in and out near Garnet, beach cottages getting cleared for the next tenant. Most of the work here happens in tight alleys and up narrow cottage stairwells, with street parking that's gone by mid-morning. We bring the right-size truck and know which alleys we can actually fit down.",
    localSections: [
      { heading: "Working PB's alleys and rentals", body: "Most Pacific Beach homes load from the alley, not the street, and a lot of them are duplexes and triplexes with units stacked up narrow exterior stairs. We're set up for it — smaller trucks that fit the alley, crews that don't mind the stairs, and timing that works around PB's mid-morning parking crunch. For landlords and property managers turning a unit between tenants, we can do same-week cleanouts and send before-and-after photos for your records." },
      { heading: "Rental turnovers and student moves", body: "A big share of our PB jobs are end-of-lease cleanouts — furniture a tenant left behind, mattresses, the contents of a garage nobody dealt with. We donate what's reusable through Goodwill and the Salvation Army and recycle what we can, so a move-out doesn't just become a dumpster run. Flat quote up front, and you only pay for the volume we actually haul." },
    ],
    faqOverrides: [
      { q: "Can you get a truck down the alley to my PB place?", a: "Almost always — we run trucks sized for Pacific Beach's alleys and know which ones are too tight. Tell us the cross streets when you book and we'll confirm the approach." },
      { q: "Do you do rental turnovers for landlords and property managers?", a: "Yes, regularly. We handle end-of-tenancy cleanouts on short notice and can send before-and-after photos for your records. A lot of our PB work is exactly this." },
      { q: "I'm on a second-floor beach cottage — can you carry it all down?", a: "Yes. Stair carries are routine here. Pricing is volume-based, not by effort or floor, so the stairs don't change your quote — you approve a flat price before we start." },
      { q: "What happens to the stuff after pickup?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most PB jobs are furniture and household goods that are easy to rehome." },
    ],
  },
  {
    slug: "junk-removal-ocean-beach",
    name: "Ocean Beach",
    zips: ["92107"],
    neighborhoods: ["OB Village", "Sunset Cliffs"],
    landmarks: ["OB Pier", "Sunset Cliffs Natural Park"],
    highways: ["I-8", "Sunset Cliffs Blvd"],
    intro: "Ocean Beach is narrow streets, older beach cottages, and a lot of rentals turning over near the OB Village and out toward Sunset Cliffs. Big trucks don't fit much of it, and parking near the pier disappears early. We run trucks that fit OB's streets and alleys and know how to work the cottages and stairs without tying up the block.",
    localSections: [
      { heading: "Narrow streets and beach cottages", body: "Much of OB is old cottages on tight lots, with alley loading and exterior stairs. We bring trucks sized for it and crews that don't mind carrying down a flight or two — and we time the job around OB's parking crunch near the Village and the pier. If your place is a tricky one to reach, tell us the cross streets when you book and we'll plan the approach so we're not blocking traffic." },
      { heading: "Rental turnovers and cottage cleanouts", body: "A lot of our OB work is rentals flipping between tenants — furniture left behind, a garage nobody dealt with, a cottage that needs clearing before the next lease. We handle move-out cleanouts on short notice, donate what's reusable through Goodwill and the Salvation Army, and recycle what we can. Flat quote up front, and you only pay for what we actually haul." },
    ],
    faqOverrides: [
      { q: "Can your truck fit OB's narrow streets and alleys?", a: "Yes — we run trucks sized for Ocean Beach and know which streets and alleys are too tight. Tell us the cross streets when you book and we'll confirm the approach." },
      { q: "My OB cottage is up a flight of stairs — is that an issue?", a: "No, stair carries are routine here. Pricing is volume-based, not by floor or effort, so the stairs don't change your quote. You approve a flat price before we start." },
      { q: "Do you do rental turnovers for landlords?", a: "Yes, regularly — end-of-tenancy cleanouts on short notice are a big share of our OB work, and we can send before-and-after photos for your records." },
      { q: "What happens to the stuff after pickup?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most OB jobs are furniture and household goods that are easy to rehome." },
    ],
  },
  {
    slug: "junk-removal-point-loma",
    name: "Point Loma",
    zips: ["92106"],
    neighborhoods: ["La Playa", "Roseville", "Wooded Area"],
    landmarks: ["Cabrillo National Monument", "Liberty Station"],
    highways: ["I-5", "Catalina Blvd"],
    intro: "Point Loma homes tend to be older, larger, and built into the hillside — La Playa down by the water, Roseville, the Wooded Area up the slope. That means stair work and long carries are the norm here, not the exception. We staff and plan for it before the truck arrives so a hillside job doesn't turn into an all-day ordeal.",
    localSections: [
      { heading: "Hillside homes and stair carries", body: "A lot of Point Loma's character comes from being built up a hill, which is great for the views and hard on a junk haul. Long stair runs, split-level layouts, and homes set well above or below the street are routine for us. We'll send the crew size the job actually needs rather than undermanning it, and we protect floors and walls on the way out. If access is genuinely tricky, tell us when you book and we'll plan the approach." },
      { heading: "Older homes, garages, and estates", body: "Point Loma's established homes often mean decades of accumulation — a garage that hasn't been cleared in years, an estate that needs emptying, a remodel's worth of old fixtures and debris. We handle the full range, set keepsakes aside on estate jobs, and donate what still has life rather than defaulting to the landfill. You get a flat quote up front and a crew that leaves the place swept." },
    ],
    faqOverrides: [
      { q: "My Point Loma home is up a long flight of stairs — is that a problem?", a: "No — hillside stair carries are the norm here and we staff for them. Pricing is volume-based, so the stairs and carry distance don't change your quote. You approve a flat price before we start." },
      { q: "Can you clear out a full garage or estate?", a: "Yes, that's a lot of our Point Loma work. We handle everything from a single garage to a full multi-level estate, set aside keepsakes, and donate what's reusable." },
      { q: "How fast can you get to Point Loma?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window fast." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-del-mar",
    name: "Del Mar",
    zips: ["92014"],
    neighborhoods: ["Del Mar Village", "Del Mar Heights", "Del Mar Mesa"],
    landmarks: ["Del Mar Racetrack", "Del Mar Fairgrounds"],
    highways: ["I-5", "Camino Del Mar"],
    intro: "Del Mar jobs lean toward larger coastal homes, hillside lots with ocean views, and a steady stream of realtor and property-manager work prepping homes to sell. Access is often a steep driveway or a gated entrance, and timelines are frequently tight around a listing. We quote flat, plan the access, and move fast when a sale's on the clock.",
    localSections: [
      { heading: "Hillside lots and gated entrances", body: "A lot of Del Mar's homes sit on slopes for the view, which means steep driveways, long carries, and the occasional gated entrance or HOA rule. We plan the approach before the truck arrives and send the crew the job actually needs. If there's a gate code, a tight turnaround, or an HOA that needs notice, tell us when you book and we'll handle it ahead of time." },
      { heading: "Listing prep on a deadline", body: "Much of our Del Mar work comes through realtors and property managers who need a home cleared and camera-ready fast. We move on your timeline — often same or next day — set keepsakes aside on estate and downsizing jobs, and donate what still has life through Goodwill and the Salvation Army. Flat quote up front, photos for your records, and a swept space when we're done." },
    ],
    faqOverrides: [
      { q: "My Del Mar home has a steep driveway and a gate — can you still do it?", a: "Yes — hillside lots and gated entrances are routine here. Share the gate code and any HOA notice requirements when you book and we'll plan the access. Pricing is volume-based, so a tricky driveway doesn't change your quote." },
      { q: "I'm a realtor with a listing on a deadline — how fast can you come?", a: "Often same or next day. A big share of our Del Mar work is listing prep on the clock. Text photos for a quick quote and we'll get you a tight arrival window." },
      { q: "Can you set aside items the family wants to keep?", a: "Always. On estate and downsizing jobs we set keepsakes aside first and only haul what you've confirmed. You do a walkthrough before we pull away." },
      { q: "Do you donate the items you remove?", a: "Yes — we donate everything reusable through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable goes to the landfill." },
    ],
  },
  { slug: "junk-removal-solana-beach", name: "Solana Beach", zips: ["92075"], neighborhoods: ["Cedros Design District"], landmarks: ["Fletcher Cove"], highways: ["I-5", "Hwy 101"], intro: "Solana Beach properties range from coastal condos to estate homes near Fletcher Cove. We've handled both." },
  {
    slug: "junk-removal-encinitas",
    name: "Encinitas",
    zips: ["92024"],
    neighborhoods: ["Leucadia", "Cardiff", "Olivenhain", "Old Encinitas"],
    landmarks: ["Moonlight Beach", "Self-Realization Fellowship"],
    highways: ["I-5", "Hwy 101", "Encinitas Blvd"],
    intro: "Encinitas covers a lot of ground — historic craftsman homes in Old Encinitas, surf bungalows in Leucadia, ranch and equestrian properties out in Olivenhain, beach condos in Cardiff. The job changes a lot depending on which one you're in: tight Hwy 101 frontage in town, long rural driveways out east. We come prepared for the version of Encinitas you're actually in.",
    localSections: [
      { heading: "From Leucadia bungalows to Olivenhain ranches", body: "An Old Encinitas or Leucadia job usually means tight street access off the 101, older homes, and the occasional steep lot down toward the beach. Out in Olivenhain it flips — long driveways, larger properties, sometimes a barn or shed full of years of accumulation. We bring the right crew and truck for whichever it is, and on the rural lots we don't mind the extra carry distance. Tell us roughly where you are when you book and we'll plan accordingly." },
      { heading: "Garage clear-outs, moves, and remodels", body: "A lot of our Encinitas work is the everyday stuff — a garage that got away from you, furniture left after a move, debris from a remodel or a yard project. We donate what's still usable through Goodwill and the Salvation Army, recycle what we can, and keep what actually has to go to the landfill to a minimum. Flat quote up front, and you only pay for the volume we haul." },
    ],
    faqOverrides: [
      { q: "Do you cover all of Encinitas — Leucadia, Cardiff, Olivenhain?", a: "Yes, all of it. Access varies a lot between beach-side Leucadia and rural Olivenhain, so tell us your neighborhood when you book and we'll bring the right setup." },
      { q: "Can you handle a rural Olivenhain property with a long driveway or a shed?", a: "Yes — larger lots, long carries, and outbuildings are routine out there. Pricing is volume-based, so the extra distance doesn't change your quote." },
      { q: "How fast can you get out to Encinitas?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "What happens to the items you take?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture, household goods, and yard debris that are easy to rehome or recycle." },
    ],
  },
  {
    slug: "junk-removal-carlsbad",
    name: "Carlsbad",
    zips: ["92008", "92009", "92010", "92011"],
    neighborhoods: ["Carlsbad Village", "La Costa", "Aviara", "Olde Carlsbad"],
    landmarks: ["LEGOLAND", "Carlsbad Flower Fields"],
    highways: ["I-5", "Palomar Airport Rd"],
    intro: "Carlsbad is one of our busiest North County markets, and it's a varied one — Village condos near the coast, La Costa and Aviara estates up in the hills, established family homes in Olde Carlsbad. We work all of it, from a single-condo furniture haul to a full estate cleanout, and we plan around the gated communities and HOA rules that come with the newer developments.",
    localSections: [
      { heading: "Village condos to La Costa estates", body: "Down near Carlsbad Village it's coastal condos and older homes with tighter access; up in La Costa and Aviara it's larger estates, gated entries, and HOA notice requirements. We handle both ends — smaller trucks and stair crews for the Village, full crews and planning for the hillside estates. If your community needs a gate code, a COI, or advance notice, tell us when you book and we'll have it sorted before we arrive." },
      { heading: "Estates, downsizing, and realtor work", body: "A good share of our Carlsbad jobs come through families downsizing or clearing an estate, and realtors prepping a home to list. We set keepsakes aside, work to your timeline, document before-and-after, and donate what still has life through Goodwill and the Salvation Army rather than defaulting to the landfill. Flat quote up front and a swept space when we leave — whether it's one room or a whole house." },
    ],
    faqOverrides: [
      { q: "Do you cover all of Carlsbad — Village, La Costa, Aviara, Olde Carlsbad?", a: "Yes, all of it. Carlsbad's a big, varied market and it's one of our busiest in North County. Tell us your neighborhood when you book and we'll bring the right crew and truck." },
      { q: "My Carlsbad community is gated and needs a COI — can you handle that?", a: "Yes. Share the gate code and any HOA or certificate-of-insurance requirements when you book and we'll have the paperwork done before we arrive." },
      { q: "Can you do a full estate or downsizing cleanout?", a: "Absolutely — that's a big part of our Carlsbad work. We set keepsakes aside, work to your timeline, and donate what's reusable. Single room or whole home, you get a flat quote up front." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-rancho-santa-fe", name: "Rancho Santa Fe", zips: ["92067"], neighborhoods: ["The Covenant", "The Crosby", "Fairbanks Ranch"], landmarks: ["RSF Golf Club"], highways: ["I-5", "Del Dios Hwy"], intro: "RSF estates need a hauler who's quiet, careful, COI-ready, and comfortable on long private drives. That's us." },
  { slug: "junk-removal-poway", name: "Poway", zips: ["92064"], neighborhoods: ["Old Poway", "Green Valley", "Bridlewood"], landmarks: ["Lake Poway", "Old Poway Park"], highways: ["I-15", "Poway Rd"], intro: "Poway homes are bigger, often on larger lots with sheds, RVs, and full garages. We bring the truck space and the crew size to handle it." },
  {
    slug: "junk-removal-rancho-bernardo",
    name: "Rancho Bernardo",
    zips: ["92127", "92128"],
    neighborhoods: ["Westwood", "The Trails"],
    landmarks: ["Rancho Bernardo Inn"],
    highways: ["I-15", "Rancho Bernardo Rd"],
    intro: "Rancho Bernardo is established master-planned North County — a lot of longtime homeowners, active-adult communities, and family homes in Westwood and The Trails. A big share of our work here is downsizing: full-house, often multi-day cleanouts handled as one coordinated job. We work to your timeline and treat a lifetime of belongings with care.",
    localSections: [
      { heading: "Downsizing and full-house cleanouts", body: "Much of our Rancho Bernardo work is longtime residents downsizing — moving to something smaller, or families handling a parent's home. These are often full-house, multi-day projects, and we treat them as one coordinated cleanout rather than a rushed haul. We set keepsakes aside, work to your timeline, and donate what still has life through Goodwill and the Salvation Army. Flat quote up front." },
      { heading: "Garages, communities, and access", body: "RB's homes range from Westwood family houses to homes in gated and active-adult communities with HOA rules. For everyday jobs it's garages, furniture, and accumulated household goods; for community access, tell us any gate code or HOA notice requirements when you book and we'll handle it ahead of time. You only pay for the volume we haul." },
    ],
    faqOverrides: [
      { q: "Can you handle a full-house downsizing cleanout?", a: "Yes — that's a big part of our Rancho Bernardo work. We treat full-house jobs as one coordinated cleanout, set keepsakes aside, and work to your timeline, even over multiple days if needed." },
      { q: "My RB community is gated with HOA rules — can you work there?", a: "Yes. Share the gate code and any HOA notice requirements when you book and we'll have it sorted before we arrive." },
      { q: "How fast can you get to Rancho Bernardo?", a: "Often same or next day for standard jobs. For larger downsizing projects we'll schedule a time that works for you. Text photos for a quick quote." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-el-cajon",
    name: "El Cajon",
    zips: ["92019", "92020", "92021"],
    neighborhoods: ["Bostonia", "Fletcher Hills", "Granite Hills"],
    landmarks: ["Cajon Speedway", "Parkway Plaza"],
    highways: ["I-8", "CA-67"],
    intro: "El Cajon is an East County hub — a broad mix of established homes in Fletcher Hills, newer subdivisions out toward Bostonia, rentals, and family properties with full garages and yards. Access is generally straightforward, and the work is mostly everyday residential cleanouts. We bring the crew and truck space to clear it in one trip where we can.",
    localSections: [
      { heading: "Garages, yards, and full-house cleanouts", body: "Most of our El Cajon work is the bread-and-butter stuff — a garage packed to the rafters, a yard cleared after a project, furniture from a move, a full-house cleanout. Properties here often have the room to accumulate, so loads can run large; we bring enough truck space and crew to handle it efficiently. Flat quote up front, and you only pay for the volume we actually haul." },
      { heading: "Rentals, downsizing, and move-outs", body: "Across El Cajon's neighborhoods and rentals we handle a steady stream of move-outs, downsizing, and end-of-tenancy cleanouts. We donate what's reusable through Goodwill and the Salvation Army, recycle what we can, and leave the space swept. For landlords and property managers, we can turn a unit on short notice and send before-and-after photos for your records." },
    ],
    faqOverrides: [
      { q: "Can you clear a full garage or whole house in El Cajon?", a: "Yes — full garages and whole-house cleanouts are routine here. We bring the truck space and crew to do it in as few trips as possible. Pricing is volume-based, so you only pay for what we haul." },
      { q: "Do you do rental turnovers for landlords and property managers?", a: "Yes, regularly. We handle end-of-tenancy cleanouts on short notice and can send before-and-after photos for your records." },
      { q: "How fast can you get to El Cajon?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "What happens to the items you remove?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture, household goods, and yard debris that are easy to rehome or recycle." },
    ],
  },
  {
    slug: "junk-removal-la-mesa",
    name: "La Mesa",
    zips: ["91941", "91942"],
    neighborhoods: ["Mt Helix", "Lake Murray", "Downtown La Mesa"],
    landmarks: ["Mt Helix Cross"],
    highways: ["I-8", "CA-94"],
    intro: "La Mesa packs a lot of variety into a small East County footprint — hilltop estates around Mt Helix, lakefront homes near Lake Murray, and condos and older bungalows in walkable Downtown La Mesa. The access changes a lot: steep hillside driveways up top, tighter downtown parking below. We plan for whichever part of La Mesa you're in.",
    localSections: [
      { heading: "From Mt Helix estates to downtown condos", body: "Up around Mt Helix it's larger homes on steep hillside lots — long driveways, grade, and carry distance to plan for. Near Lake Murray it's established family homes, and in Downtown La Mesa it's condos, bungalows, and tighter street parking. We bring the crew and truck each one calls for, and we'd rather send an extra hand than risk a tight hillside turn. Tell us your part of town when you book." },
      { heading: "Downsizing, estates, and garage clear-outs", body: "A good share of our La Mesa work is longtime homeowners downsizing or families clearing an estate, plus everyday garage and yard cleanouts. On estate and downsizing jobs we set keepsakes aside and work to your timeline, and we donate what still has life through Goodwill and the Salvation Army. Flat quote up front and a swept space when we leave." },
    ],
    faqOverrides: [
      { q: "My La Mesa home is up a steep Mt Helix driveway — is that a problem?", a: "No — hillside access is routine here and we staff for it. Pricing is volume-based, so the grade and carry distance don't change your quote. You approve a flat price before we start." },
      { q: "Can you help with a downsizing or estate cleanout?", a: "Yes, that's a big part of our La Mesa work. We set keepsakes aside, work to your timeline, and donate what's reusable. Single room or whole home, you get a flat quote up front." },
      { q: "How fast can you get to La Mesa?", a: "Often same or next day. Text photos for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-city-heights", name: "City Heights", zips: ["92105", "92115"], neighborhoods: ["Cherokee Point", "Castle", "Fairmount Village"], highways: ["I-15", "I-805", "El Cajon Blvd"], intro: "City Heights — fast turnover, multi-family properties, and apartment cleanouts. We're a property-management partner across the neighborhood." },
  { slug: "junk-removal-linda-vista", name: "Linda Vista", zips: ["92111"], neighborhoods: ["Birdland", "Tecolote Canyon"], landmarks: ["USD"], highways: ["I-805", "Linda Vista Rd"], intro: "Linda Vista — USD-adjacent rental turnover, family homes, and post-storm yard work. We're here for it." },
  { slug: "junk-removal-bay-park", name: "Bay Park", zips: ["92110"], neighborhoods: ["Bay Park Heights"], landmarks: ["Mission Bay"], highways: ["I-5", "I-8"], intro: "Bay Park — the neighborhood directly north of Mission Bay where we're based on Morena Blvd. We're literally minutes from your front door." },
  { slug: "junk-removal-clairemont", name: "Clairemont", zips: ["92117"], neighborhoods: ["Clairemont Mesa East", "North Clairemont", "Bay Ho", "Bay Park"], landmarks: ["Clairemont Square"], highways: ["I-5", "I-805", "CA-52"], intro: "Clairemont is JunkMD+'s home neighborhood — we're located here on Morena Blvd. Same-day pickup is always on the table." },
  {
    slug: "junk-removal-north-park",
    name: "North Park",
    zips: ["92104"],
    neighborhoods: ["Burlingame", "Altadena"],
    landmarks: ["North Park Theatre", "Morley Field"],
    highways: ["I-805", "University Ave"],
    intro: "North Park is classic San Diego craftsman and bungalow territory — older homes on tight lots, alley loading off the back, and street-parking-only out front. It's one of the city's busiest neighborhoods, with a mix of longtime homeowners, renters, and homes being renovated. The work here usually means working an alley or carrying through an older, narrower house. We come set up for it.",
    localSections: [
      { heading: "Craftsman homes and alley loading", body: "Most North Park homes are older craftsman and bungalow builds on small lots, and a lot of them load from the alley rather than the street. Narrow doorways, tight hallways, and detached garages off the back are the norm. We bring trucks that fit the alleys and crews used to maneuvering through older homes without dinging a doorframe. If your place is alley-access or street-parking-only, tell us when you book and we'll plan the approach." },
      { heading: "Renovations, move-outs, and garage clear-outs", body: "North Park sees a lot of renovation and turnover — a bungalow being updated, a rental changing hands, a garage or basement that's collected years of stuff. We handle remodel debris, full move-out cleanouts, and everyday garage clear-outs, donate what's reusable through Goodwill and the Salvation Army, and recycle what we can. Flat quote up front, and you only pay for the volume we actually haul." },
    ],
    faqOverrides: [
      { q: "My North Park home loads from the alley — is that a problem?", a: "Not at all — alley loading is the norm here and we run trucks that fit. Tell us the cross streets and whether it's alley or street access when you book and we'll plan the approach." },
      { q: "Can you get furniture out of an older bungalow with narrow doorways?", a: "Yes, that's routine in North Park. Our crews are used to maneuvering through older homes carefully. Pricing is volume-based, so a tricky carry doesn't change your quote." },
      { q: "Do you take renovation and remodel debris?", a: "Yes — remodel debris is common here. We haul construction and renovation waste along with furniture and household junk. Text photos for a quick quote." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-south-park", name: "South Park", zips: ["92102"], neighborhoods: ["South Park Village"], landmarks: ["Balboa Park (south)"], highways: ["I-5", "CA-94"], intro: "South Park's historic craftsman homes and walkable streets need a hauler that respects the neighborhood character. JunkMD+ does." },
  { slug: "junk-removal-san-carlos", name: "San Carlos", zips: ["92119"], neighborhoods: ["Cowles Mountain area"], landmarks: ["Cowles Mountain", "Lake Murray"], highways: ["I-8", "Navajo Rd"], intro: "San Carlos — east of Mission Trails — has lots of original-owner homes ready for major cleanouts. We handle decades of accumulated stuff routinely." },
  { slug: "junk-removal-carmel-valley", name: "Carmel Valley", zips: ["92130"], neighborhoods: ["Pacific Highlands Ranch", "Del Mar Heights"], landmarks: ["One Paseo"], highways: ["I-5", "CA-56"], intro: "Carmel Valley families call us during home sales, garage cleanouts, and home gym swaps. We respect HOA rules and gated entry." },
  { slug: "junk-removal-torrey-pines", name: "Torrey Pines", zips: ["92037"], neighborhoods: ["Torrey Pines area"], landmarks: ["Torrey Pines State Reserve", "Torrey Pines Golf Course"], highways: ["I-5", "N Torrey Pines Rd"], intro: "Torrey Pines cliff-side homes and condos — we handle the gated communities and the strict HOA rules with COIs ready to go." },
  { slug: "junk-removal-sorrento-valley", name: "Sorrento Valley", zips: ["92121"], landmarks: ["Sorrento Valley Business Park"], highways: ["I-5", "I-805", "Carmel Mountain Rd"], intro: "Sorrento Valley business park cleanouts — biotech, tech, R&D office turnovers. After-hours work, COI-ready." },
  { slug: "junk-removal-mission-valley", name: "Mission Valley", zips: ["92108", "92120"], neighborhoods: ["Mission Valley West", "Mission Valley East"], landmarks: ["Fashion Valley", "Westfield Mission Valley", "USD"], highways: ["I-8", "I-15"], intro: "Mission Valley — condos, apartments, and shopping center turnovers. We handle the high-rise loading docks and the strict HOA rules." },
  { slug: "junk-removal-kearny-mesa", name: "Kearny Mesa", zips: ["92111", "92123"], landmarks: ["Convoy District", "Aero Dr corridor"], highways: ["I-15", "CA-52", "CA-163"], intro: "Kearny Mesa office-park cleanouts and Convoy District restaurant closeouts — JunkMD+ handles them after hours, on weekends, on the building schedule." },
  { slug: "junk-removal-tierrasanta", name: "Tierrasanta", zips: ["92124"], landmarks: ["Mission Trails Regional Park"], highways: ["I-15", "CA-52"], intro: "Tierrasanta — the 'island in the hills' — single-family homes ready for cleanouts. We're nearby." },
  { slug: "junk-removal-rancho-penasquitos", name: "Rancho Peñasquitos", zips: ["92129"], landmarks: ["PQ Town Center", "Black Mountain Open Space"], highways: ["I-15", "CA-56"], intro: "PQ family-home cleanouts — we're a regular here, handling everything from garage sweeps to estate cleanouts." },
  { slug: "junk-removal-4s-ranch", name: "4S Ranch", zips: ["92127"], landmarks: ["4S Commons"], highways: ["I-15", "Camino Del Norte"], intro: "4S Ranch's planned-community homes mean garages, sheds, and well-organized cleanouts. We know the area." },
  { slug: "junk-removal-university-city", name: "University City", zips: ["92122"], neighborhoods: ["Golden Triangle", "UTC"], landmarks: ["UTC Westfield", "UCSD"], highways: ["I-5", "I-805", "Genesee Ave"], intro: "UTC and UC — condos, towers, family homes near UCSD. We coordinate with strict HOAs and high-rise loading docks." },
  {
    slug: "junk-removal-santee",
    name: "Santee",
    zips: ["92071"],
    landmarks: ["Santee Lakes"],
    highways: ["CA-52", "CA-67"],
    intro: "Santee is East County suburban — spacious single-family homes with full garages, sheds, RVs, and big yards that collect a lot over the years. Access is generally easy, but the loads run large. We bring the truck space and crew to clear a packed garage, a yard project, or a full house in as few trips as possible.",
    localSections: [
      { heading: "Big garages, sheds, and yards", body: "Santee properties tend to have room — two- and three-car garages, sheds, side yards, sometimes an RV pad — which means the cleanouts here run bigger than a condo job. We come with enough capacity to handle a fully packed garage or years of accumulated yard and shed contents in one trip where we can. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Moves, downsizing, and full-house clear-outs", body: "We handle a steady mix of move-outs, downsizing, and full-house cleanouts across Santee. We donate what's reusable through Goodwill and the Salvation Army, recycle what we can, and leave the space swept. On downsizing and estate jobs we set keepsakes aside and work to your timeline." },
    ],
    faqOverrides: [
      { q: "Can you handle a big garage, shed, and yard in one visit?", a: "Usually, yes — bigger loads are common in Santee and we bring enough truck space and crew to clear them in as few trips as possible. Pricing is volume-based, so you only pay for what we haul." },
      { q: "Do you take yard debris and shed contents?", a: "Yes — yard waste, shed clear-outs, old furniture, and general junk are all routine here. Text photos for a quick quote." },
      { q: "How fast can you get to Santee?", a: "Often same or next day. Send photos of what needs to go and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-spring-valley", name: "Spring Valley", zips: ["91977", "91978"], highways: ["CA-94", "I-805"], intro: "Spring Valley — east-county family homes and yard work. We're here." },
  {
    slug: "junk-removal-national-city",
    name: "National City",
    zips: ["91950"],
    landmarks: ["Westfield Plaza Bonita"],
    highways: ["I-5", "I-805"],
    intro: "National City is a dense South Bay mix of residential, rental, and commercial property, and a lot of our work here is volume — property managers, post-eviction cleanouts, and units turning over fast. Access ranges from older single-family homes to multi-family buildings. We're set up to handle the steady, high-turnover work this area generates.",
    localSections: [
      { heading: "Property managers and turnover work", body: "A big share of our National City work comes through property managers and landlords — multi-family buildings, rentals turning over, post-eviction cleanouts where a unit needs to be cleared fast and completely. We handle these on short notice, document before-and-after for your records, and donate what's reusable through Goodwill and the Salvation Army rather than just dumping. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Residential and commercial cleanouts", body: "Beyond turnover work, we clear out homes, garages, and small commercial spaces across National City. Whether it's a single-family home, an apartment, or a storefront being cleared, we bring the right crew and truck, recycle what we can, and leave the space swept." },
    ],
    faqOverrides: [
      { q: "Do you do post-eviction and turnover cleanouts for property managers?", a: "Yes — that's a big part of our National City work. We clear units fast and completely on short notice and document before-and-after for your records." },
      { q: "Can you handle multi-family and commercial spaces, not just homes?", a: "Yes — residential, multi-family, and small commercial cleanouts are all routine here. Tell us what you've got when you book and we'll bring the right crew." },
      { q: "How fast can you get to National City?", a: "Often same or next day, and we move fast on turnover jobs. Text photos for a quick quote and we'll get you a tight arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-chula-vista",
    name: "Chula Vista",
    zips: ["91910", "91911", "91913", "91914", "91915"],
    neighborhoods: ["Eastlake", "Otay Ranch", "Bonita-adjacent"],
    landmarks: ["Otay Ranch Town Center"],
    highways: ["I-5", "I-805", "CA-125"],
    intro: "Chula Vista is big and split in two — the older western neighborhoods near downtown and the bay, and the master-planned eastern communities like Eastlake and Otay Ranch with their HOAs and gated entries. We work all of it, and the job changes a lot between the two: established homes and rentals on the west side, newer family homes with association rules out east. We plan for whichever side you're on.",
    localSections: [
      { heading: "West side homes and east side master-planned communities", body: "Western Chula Vista is older single-family homes, rentals, and tighter lots near downtown and the bayfront. Out east in Eastlake, Otay Ranch, and the newer developments, it's master-planned communities with gate codes, HOA notice rules, and sometimes COI requirements before a truck can come through. We handle both — just tell us your neighborhood when you book and, if you're in a gated community, the access details so we can sort any paperwork ahead of time." },
      { heading: "Family homes, garages, and move-outs", body: "A lot of our Chula Vista work is everyday residential — a garage that filled up over the years, furniture from a move, a full-house cleanout. We donate what's still usable through Goodwill and the Salvation Army, recycle what we can, and keep landfill to a minimum. Flat quote up front, and you only pay for the volume we actually haul." },
    ],
    faqOverrides: [
      { q: "Do you cover both west Chula Vista and the Eastlake/Otay Ranch side?", a: "Yes, all of Chula Vista. The two sides are pretty different — older homes west, master-planned communities east — so tell us your neighborhood when you book and we'll bring the right setup." },
      { q: "My Eastlake community is gated and has HOA rules — can you handle that?", a: "Yes. Share the gate code and any HOA notice or certificate-of-insurance requirements when you book and we'll have the paperwork sorted before we arrive." },
      { q: "How fast can you get to Chula Vista?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-imperial-beach",
    name: "Imperial Beach",
    zips: ["91932"],
    landmarks: ["IB Pier"],
    highways: ["I-5", "Palm Ave"],
    intro: "Imperial Beach is a small, laid-back South Bay coastal town — beach cottages, rentals, and family homes near the pier and the bay. A lot of the work here is rental turnover and cottage cleanouts, often with tight street parking and the occasional stair carry. We bring the right-size truck and know how to work the coastal streets.",
    localSections: [
      { heading: "Beach cottages and rental turnovers", body: "Much of Imperial Beach is older cottages and rentals on tight lots near the water, with limited street parking and exterior stairs. We bring trucks sized for it and crews used to carrying from places a bigger truck can't reach. For landlords turning a unit between tenants, we handle move-out cleanouts on short notice and can send before-and-after photos for your records." },
      { heading: "Family homes and garage clear-outs", body: "Beyond the rentals, we clear out family homes, garages, and yards across Imperial Beach. We donate what's still usable through Goodwill and the Salvation Army, recycle what we can, and leave the space swept. Flat quote up front, and you only pay for the volume we haul." },
    ],
    faqOverrides: [
      { q: "Can your truck handle the tight streets near the IB pier?", a: "Yes — we run trucks sized for Imperial Beach's coastal streets and plan the approach around parking. Tell us the cross streets when you book and we'll confirm." },
      { q: "Do you do rental turnovers for landlords?", a: "Yes, regularly — quick move-out cleanouts are a big share of our IB work, and we can send before-and-after photos for your records." },
      { q: "My cottage is up a flight of stairs — is that an issue?", a: "No, stair carries are routine here. Pricing is volume-based, so the stairs don't change your quote. You approve a flat price before we start." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-rolando", name: "Rolando", zips: ["92115"], landmarks: ["SDSU"], highways: ["I-8", "El Cajon Blvd"], intro: "Rolando — SDSU-adjacent, family homes, rentals. We handle the turnover season." },
  { slug: "junk-removal-old-town", name: "Old Town", zips: ["92110"], landmarks: ["Old Town State Park"], highways: ["I-5", "I-8"], intro: "Old Town historic district — small commercial properties, restaurants, residences. We're nearby." },
  {
    slug: "junk-removal-hillcrest",
    name: "Hillcrest",
    zips: ["92103"],
    landmarks: ["Balboa Park", "UC San Diego Medical Center"],
    highways: ["I-5", "CA-163"],
    intro: "Hillcrest is dense and vertical — condos, lofts, and apartment buildings packed along the canyon edges near Balboa Park, with street parking that's hard to come by and a lot of buildings that load through a dock or a single elevator. Most of our Hillcrest work is condos and rentals, and the challenge is rarely the volume — it's the access. We plan the building logistics before we show up.",
    localSections: [
      { heading: "Condos, lofts, and building access", body: "Most Hillcrest jobs are inside a building — a condo on the fourth floor, a loft off a shared elevator, an apartment that loads through a back dock. The work itself is usually straightforward; getting it out cleanly is the part that takes planning. We coordinate elevator timing, handle any building COI or reservation requirements, and bring trucks that fit Hillcrest's tight street parking. Tell us your building setup when you book and we'll sort the logistics ahead of time." },
      { heading: "Rentals and quick turnovers", body: "A lot of our Hillcrest work is rental turnover — a tenant moved out and left furniture, a unit needs clearing before the next lease, a landlord needs it done fast. We handle move-out cleanouts on short notice, donate what's reusable through Goodwill and the Salvation Army, and can send before-and-after photos if you're managing the property. Flat quote up front, and you only pay for the volume we haul." },
    ],
    faqOverrides: [
      { q: "My Hillcrest condo is on an upper floor with one elevator — can you handle it?", a: "Yes, that's routine here. We coordinate elevator timing and handle any building reservation or COI requirements. Pricing is volume-based, so the floor and elevator don't change your quote." },
      { q: "Where do your trucks park on these tight Hillcrest streets?", a: "We run trucks sized for the neighborhood and plan the approach around the parking situation. Tell us your building and cross streets when you book and we'll confirm before we arrive." },
      { q: "Do you do rental turnovers for landlords and property managers?", a: "Yes, regularly — quick move-out cleanouts are a big share of our Hillcrest work, and we can send before-and-after photos for your records." },
      { q: "What happens to the items you remove?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture and household goods that are easy to rehome." },
    ],
  },
  {
    slug: "junk-removal-mission-beach",
    name: "Mission Beach",
    zips: ["92109"],
    landmarks: ["Belmont Park", "Mission Bay"],
    highways: ["I-5", "Mission Bay Dr"],
    intro: "Mission Beach is about as tight as it gets in San Diego — narrow lots packed between the bay and the ocean, alley access, boardwalk rules, and vacation rentals turning over constantly near Belmont Park. Street parking is a non-starter most of the year. We bring the right-size truck, work the alleys, and time jobs around the rental and boardwalk traffic.",
    localSections: [
      { heading: "Alleys, boardwalk, and tight lots", body: "Mission Beach homes are wedged onto small lots with alley loading and almost no street parking, and the boardwalk has its own access rules. We're set up for it — smaller trucks that fit the alleys, crews used to carrying from places a big truck can't reach, and timing that works around peak boardwalk and rental traffic. Tell us where you are between the bay and the ocean when you book and we'll plan the approach." },
      { heading: "Vacation rental turnovers", body: "A big share of our Mission Beach work is vacation rentals flipping between guests and tenants — furniture to clear, a unit to reset, a garage full of leftovers. We move fast on short notice, donate what's reusable through Goodwill and the Salvation Army, and recycle what we can. Flat quote up front, photos for your records if you're managing the property, and you only pay for the volume we haul." },
    ],
    faqOverrides: [
      { q: "There's nowhere to park in Mission Beach — how does that work?", a: "We plan for it. Our trucks load from the alley where possible and we time jobs around the boardwalk and rental traffic. Tell us your location between the bay and ocean when you book and we'll sort the approach." },
      { q: "Can you handle a vacation rental turnover on short notice?", a: "Yes — that's a lot of our Mission Beach work. We do quick turnover cleanouts and can send before-and-after photos if you're managing the property." },
      { q: "My place is up stairs off the alley — can you still do it?", a: "Yes, that's standard here. Pricing is volume-based, so the alley access and stairs don't change your quote — you approve a flat price before we start." },
      { q: "Do you donate the items you remove?", a: "Yes — we donate everything reusable through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable goes to the landfill." },
    ],
  },
  {
    slug: "junk-removal-coronado",
    name: "Coronado",
    zips: ["92118"],
    landmarks: ["Hotel del Coronado", "Coronado Bridge"],
    highways: ["CA-75"],
    intro: "Coronado work means crossing the bridge and dealing with island logistics — historic homes near Orange Avenue, condos along the Strand, and a fair amount of estate and listing-prep work. Parking and access are tighter than the wide streets suggest, and some buildings have their own rules. We plan the trip and the paperwork before we head over.",
    localSections: [
      { heading: "Island access and building rules", body: "Getting to Coronado is half the job — we plan around bridge traffic and the island's parking limits so we arrive in your window and don't tie up a space all afternoon. For condos along the Strand and newer buildings, there are often elevator reservations or certificate-of-insurance requirements; tell us the building when you book and we'll have that handled before we show up. Historic homes near Orange Avenue get a careful hand on the way out." },
      { heading: "Estates, listings, and downsizing", body: "A lot of our Coronado jobs come through families clearing an estate or realtors prepping a home to list. Both deserve patience — we set keepsakes aside, document before-and-after, and donate what still has life through Goodwill and the Salvation Army instead of defaulting to the landfill. Whether it's a single condo's worth of furniture or a full home, you get a flat quote up front and a swept space when we leave." },
    ],
    faqOverrides: [
      { q: "Do you serve Coronado even though it's across the bridge?", a: "Yes, regularly. We plan around bridge traffic and island parking so we still hit your 2-hour arrival window. The crossing doesn't add a surcharge — pricing is volume-based." },
      { q: "My Coronado condo building needs a COI or elevator reservation — can you handle that?", a: "Yes. Tell us the building when you book and we'll sort the certificate of insurance and any elevator or access reservation before we arrive." },
      { q: "Can you help with an estate or a home I'm listing?", a: "Absolutely — that's a big share of our Coronado work. We set keepsakes aside, work to your timeline, and donate what's reusable. Listing-prep cleanouts are routine for us." },
      { q: "What happens to the items you remove?", a: "We donate anything reusable to local charities, recycle what we can, and responsibly dispose of the rest. Most jobs here are furniture and household goods that are easy to rehome." },
    ],
  },
  { slug: "junk-removal-bonita", name: "Bonita", zips: ["91902"], landmarks: ["Bonita Golf Club"], highways: ["I-805", "CA-54"], intro: "Bonita — semi-rural homes with horses, sheds, and big yards. We come prepared for the larger lots." },
  { slug: "junk-removal-lemon-grove", name: "Lemon Grove", zips: ["91945"], highways: ["CA-94", "Federal Blvd"], intro: "Lemon Grove cleanouts — affordable single-family homes ready for major yard and garage work." },
  // ───── Expansion ─────
  {
    slug: "junk-removal-mira-mesa",
    name: "Mira Mesa",
    zips: ["92126"],
    landmarks: ["Miramar Marine Corps Air Station"],
    highways: ["I-15", "I-805", "CA-805"],
    intro: "Mira Mesa is a big, established family neighborhood in the middle of the city — single-family homes, townhomes, and a steady stream of moves, partly because it sits right next to MCAS Miramar. Most of the work here is everyday residential: garages, move-outs, and full-house cleanouts. Access is generally easy, and we bring the truck space and crew to clear a big load in one trip where we can.",
    localSections: [
      { heading: "Family homes, garages, and move-outs", body: "Most Mira Mesa properties are family homes and townhomes with garages, yards, and the usual accumulation of years — which is exactly the kind of everyday cleanout we do most. Access is generally straightforward, so the job is usually about capacity: bringing enough truck space and crew to clear a packed garage or a full house efficiently. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Moves in and out", body: "Sitting right next to MCAS Miramar, Mira Mesa sees a lot of families relocating, and we handle a steady stream of move-in and move-out cleanouts — furniture left behind, a garage to empty, a whole house to clear on a deadline. We move fast, donate what's reusable through Goodwill and the Salvation Army, and give you a flat quote up front so there are no surprises on moving day." },
    ],
    faqOverrides: [
      { q: "Can you clear a full garage or whole house in Mira Mesa?", a: "Yes — that's a big share of our work here. We bring the truck space and crew to handle large cleanouts in as few trips as possible. Pricing is volume-based, so you only pay for what we haul." },
      { q: "Can you handle a move-out on a tight timeline?", a: "Yes, regularly. Move-outs are common in Mira Mesa and we move fast. Text photos for a quick quote and we'll get you a tight arrival window, often same or next day." },
      { q: "How fast can you get to Mira Mesa?", a: "Often same or next day, since it's central. Send photos of what needs to go and we'll usually get you a 2-hour arrival window." },
      { q: "What happens to the items you remove?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture and household goods that are easy to rehome." },
    ],
  },
  {
    slug: "junk-removal-scripps-ranch",
    name: "Scripps Ranch",
    zips: ["92131"],
    landmarks: ["Lake Miramar"],
    highways: ["I-15"],
    intro: "Scripps Ranch is a family-oriented North City community — established homes among the eucalyptus, larger lots, and a lot of longtime owners. The work here is mostly everyday residential: garages, downsizing, and full-house cleanouts, with generally easy access and loads that can run large. We bring the capacity to clear it efficiently.",
    localSections: [
      { heading: "Family homes, garages, and big loads", body: "Scripps Ranch homes tend to be family houses on comfortable lots with full garages and yards, so cleanouts here often run larger than average. Access is usually straightforward, so the job is about capacity — bringing enough truck space and crew to clear a packed garage or a full house in as few trips as we can. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Downsizing and move-outs", body: "We handle a steady stream of downsizing and move-outs across Scripps Ranch's established neighborhoods. On downsizing and estate jobs we set keepsakes aside and work to your timeline, donate what's reusable through Goodwill and the Salvation Army, and leave the space swept." },
    ],
    faqOverrides: [
      { q: "Can you clear a full garage or whole house in Scripps Ranch?", a: "Yes — that's a lot of our work here. We bring the truck space and crew to handle large cleanouts in as few trips as possible. Pricing is volume-based, so you only pay for what we haul." },
      { q: "Can you help with a downsizing cleanout?", a: "Yes — we set keepsakes aside, work to your timeline, and donate what's reusable. Single room or whole home, you get a flat quote up front." },
      { q: "How fast can you get to Scripps Ranch?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-allied-gardens", name: "Allied Gardens", zips: ["92120"], landmarks: ["Mission Trails Regional Park"], highways: ["I-8", "I-15"], intro: "Allied Gardens — original-owner family homes east of Mission Valley. Decades of accumulated stuff is our specialty." },
  { slug: "junk-removal-del-cerro", name: "Del Cerro", zips: ["92120"], landmarks: ["Lake Murray", "SDSU"], highways: ["I-8"], intro: "Del Cerro hillside homes — we handle the long stair runs and tight driveways." },
  { slug: "junk-removal-college-area", name: "College Area", zips: ["92115"], landmarks: ["SDSU"], highways: ["I-8", "I-15"], intro: "College Area — SDSU-adjacent rentals, lots of turnover, lots of mattresses. We're a regular here." },
  { slug: "junk-removal-pacific-highlands-ranch", name: "Pacific Highlands Ranch", zips: ["92130"], highways: ["CA-56"], intro: "PHR — Carmel Valley's newer extension. Family homes, garage cleanouts, gym-equipment hauls." },
  { slug: "junk-removal-mission-hills", name: "Mission Hills", zips: ["92103"], landmarks: ["Presidio Park"], highways: ["I-5", "I-8"], intro: "Mission Hills' historic Spanish-style homes need a hauler who's careful with original details. JunkMD+ is." },
  { slug: "junk-removal-bankers-hill", name: "Bankers Hill", zips: ["92103"], landmarks: ["Balboa Park"], highways: ["I-5"], intro: "Bankers Hill condos, towers, and historic homes between Hillcrest and Downtown. We coordinate with high-rise loading docks." },
  { slug: "junk-removal-la-jolla-shores", name: "La Jolla Shores", zips: ["92037"], landmarks: ["La Jolla Shores Beach", "Scripps Pier"], highways: ["I-5"], intro: "La Jolla Shores — beach-adjacent homes with strict gated-entry rules. We coordinate access." },
  { slug: "junk-removal-sunset-cliffs", name: "Sunset Cliffs", zips: ["92107"], landmarks: ["Sunset Cliffs Natural Park"], highways: ["I-5", "I-8"], intro: "Sunset Cliffs — cliff-edge homes with tight access. We bring the right truck for the right driveway." },
  { slug: "junk-removal-eastlake", name: "Eastlake (Chula Vista)", zips: ["91914", "91915"], landmarks: ["Eastlake Trails"], highways: ["I-805", "CA-125"], intro: "Eastlake's master-planned communities — we know the streets, the HOAs, and the loading rules." },
  { slug: "junk-removal-otay-ranch", name: "Otay Ranch", zips: ["91913", "91914"], landmarks: ["Otay Ranch Town Center"], highways: ["I-805", "CA-125"], intro: "Otay Ranch — Chula Vista's biggest planned community. Family homes ready for garage, attic, and shed cleanouts." },
  {
    slug: "junk-removal-san-ysidro",
    name: "San Ysidro",
    zips: ["92173"],
    landmarks: ["San Ysidro Port of Entry"],
    highways: ["I-5", "I-805"],
    intro: "San Ysidro is San Diego's southernmost neighborhood, right at the border crossing — a busy mix of residential and commercial property. We come down regularly for home and apartment cleanouts as well as small-business and commercial clear-outs. The work here leans toward turnover and volume, and we're set up for both.",
    localSections: [
      { heading: "Residential and commercial cleanouts", body: "San Ysidro's mix means we're clearing everything from apartments and family homes to small commercial spaces and storefronts near the port of entry. We bring the right crew and truck for whichever it is, handle turnover and move-out work on short notice, and donate what's reusable through Goodwill and the Salvation Army. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Property managers and turnover", body: "We handle a steady stream of rental turnover and property-manager work in San Ysidro — units to clear between tenants, post-move cleanouts, accumulated junk from a garage or yard. We move fast, document before-and-after for your records, and recycle what we can." },
    ],
    faqOverrides: [
      { q: "Do you serve San Ysidro even though it's right at the border?", a: "Yes, regularly. We come down for residential and commercial cleanouts across San Ysidro. Text photos for a quick quote and we'll get you an arrival window." },
      { q: "Can you handle commercial and small-business cleanouts?", a: "Yes — storefronts, offices, and small commercial spaces along with homes and apartments. Tell us what you've got when you book and we'll bring the right crew." },
      { q: "Do you do rental turnovers for landlords and property managers?", a: "Yes — quick turnover and move-out cleanouts are common here, and we can send before-and-after photos for your records." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-otay-mesa", name: "Otay Mesa", zips: ["92154"], landmarks: ["Brown Field Airport"], highways: ["CA-905", "CA-125"], intro: "Otay Mesa — industrial parks and family neighborhoods. We're set up for both residential and commercial work down south." },
  {
    slug: "junk-removal-escondido",
    name: "Escondido",
    zips: ["92025", "92026", "92027", "92029"],
    landmarks: ["San Diego Zoo Safari Park", "Lake Hodges"],
    highways: ["I-15", "CA-78"],
    intro: "Escondido is inland North County — larger lots, established neighborhoods, and a fair number of homes on bigger parcels with sheds, yards, and garages that collect years of stuff. Access is usually easier than the coast, but the loads tend to be bigger. We bring the truck space and crew to clear a full garage, a yard project, or a whole house in one trip where we can.",
    localSections: [
      { heading: "Larger lots and bigger loads", body: "A lot of Escondido properties have room — bigger garages, sheds, yards, sometimes outbuildings — which means the cleanouts here tend to run larger than a coastal condo job. We come with enough truck space and crew to handle it in as few trips as possible, whether it's a garage that got away from you, accumulated yard debris, or a full-house clear-out. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Downsizing, estates, and move-outs", body: "We handle a steady mix of downsizing, estate clear-outs, and move-outs across Escondido's established neighborhoods. On estate and downsizing jobs we set keepsakes aside and work to your timeline, and we donate what still has life through Goodwill and the Salvation Army rather than defaulting to the landfill. A swept space when we leave, every time." },
    ],
    faqOverrides: [
      { q: "Do you handle larger properties with sheds and big yards?", a: "Yes — bigger lots and bigger loads are common in Escondido and we come prepared with the truck space and crew to clear them efficiently. Pricing is volume-based, so you only pay for what we haul." },
      { q: "Can you clear a full garage or a whole house in one visit?", a: "Usually, yes. We bring enough capacity to handle large cleanouts in as few trips as possible. Text photos for a quick quote and we'll plan the right crew and truck." },
      { q: "How fast can you get out to Escondido?", a: "Often same or next day. Send photos of what needs to go and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-san-marcos",
    name: "San Marcos",
    zips: ["92069", "92078"],
    landmarks: ["Cal State San Marcos"],
    highways: ["CA-78", "I-15"],
    intro: "San Marcos is a North County university town — Cal State San Marcos drives a steady cycle of student rentals turning over, alongside established family neighborhoods and newer developments up the hills. The work splits between quick rental cleanouts near campus and bigger family-home and garage jobs elsewhere. We handle both, and the turnover season keeps us busy here.",
    localSections: [
      { heading: "Student rentals and family homes", body: "Near Cal State San Marcos it's rentals turning over between leases — furniture left behind, a unit to clear before the next tenant, often on a tight end-of-semester timeline. Out in the family neighborhoods and newer hillside developments, it's garages, downsizing, and full-house cleanouts. We bring the right setup for each and move fast during turnover season. Tell us your neighborhood when you book and we'll plan accordingly." },
      { heading: "Garages, moves, and yard clear-outs", body: "A lot of our San Marcos work is the everyday stuff — a garage that filled up, debris from a yard project, furniture from a move. We donate what's still usable through Goodwill and the Salvation Army, recycle what we can, and keep landfill to a minimum. Flat quote up front, and you only pay for the volume we actually haul." },
    ],
    faqOverrides: [
      { q: "Do you do student rental turnovers near Cal State San Marcos?", a: "Yes, regularly — quick end-of-lease cleanouts are a big share of our San Marcos work, especially around turnover season. We can send before-and-after photos for landlords and property managers." },
      { q: "Can you clear a full garage or whole house?", a: "Yes — from a single garage to a full-house cleanout. We bring the truck space and crew to do it in as few trips as possible. Pricing is volume-based, so you only pay for what we haul." },
      { q: "How fast can you get to San Marcos?", a: "Often same or next day. Text photos of what needs to go for a quick quote and we'll usually get you a 2-hour arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-vista", name: "Vista", zips: ["92081", "92083", "92084"], highways: ["CA-78"], intro: "Vista North County cleanouts — JunkMD+ services the area on a same-week schedule." },
  {
    slug: "junk-removal-oceanside",
    name: "Oceanside",
    zips: ["92054", "92056", "92057"],
    landmarks: ["Oceanside Pier", "Camp Pendleton"],
    highways: ["I-5", "CA-78"],
    intro: "Oceanside covers a lot — beach rentals and older cottages near the pier, established neighborhoods inland, and a steady stream of moves given how close it sits to Camp Pendleton. Between the coastal turnover and families relocating in and out, there's always something to clear. We bring the right-size truck for the beach streets and the crew for a full-house move-out.",
    localSections: [
      { heading: "Coastal rentals and inland family homes", body: "Near the pier and the harbor it's beach cottages, condos, and rentals with tight street parking and the occasional stair carry. Head inland and it's larger family homes and established neighborhoods with easier access but bigger loads. We bring the setup each one needs, and we time the coastal jobs around Oceanside's summer parking crunch. Tell us roughly where you are when you book and we'll plan accordingly." },
      { heading: "Moves and full-house clear-outs", body: "Sitting right next to Camp Pendleton, Oceanside sees a lot of families moving in and out, and we handle a steady stream of move-out and move-in cleanouts — furniture left behind, a garage to empty, a whole house to clear on a tight timeline. We move fast, donate what's reusable through Goodwill and the Salvation Army, and give you a flat quote up front so there are no surprises on moving day." },
    ],
    faqOverrides: [
      { q: "Can you handle a full-house move-out on a tight timeline?", a: "Yes — move-outs are a big share of our Oceanside work, and we move fast. Text photos for a quick quote and we'll get you a tight arrival window, often same or next day." },
      { q: "Do you work the beach-side streets near the pier?", a: "Yes. We run trucks sized for Oceanside's coastal streets and plan around the summer parking crunch. Tell us the cross streets when you book and we'll confirm the approach." },
      { q: "Can you carry items down from a second-floor coastal rental?", a: "Yes, stair carries are routine. Pricing is volume-based, not by floor or effort, so the stairs don't change your quote — you approve a flat price before we start." },
      { q: "What happens to the items you remove?", a: "We donate anything reusable to local charities, recycle what we can, and dispose of the rest responsibly. Most jobs here are furniture and household goods that are easy to rehome." },
    ],
  },
  { slug: "junk-removal-fallbrook", name: "Fallbrook", zips: ["92028"], highways: ["I-15", "CA-76"], intro: "Fallbrook — semi-rural North County with avocado groves and big lots. We make the trip out." },
  {
    slug: "junk-removal-lakeside",
    name: "Lakeside",
    zips: ["92040"],
    landmarks: ["Lindo Lake"],
    highways: ["CA-67", "I-8"],
    intro: "Lakeside is semi-rural East County — homes on bigger lots with sheds, RVs, detached garages, and plenty of yard. The loads here tend to run large and sometimes include heavy or bulky outdoor items. We make the trip out with enough truck space and crew to clear a big property in as few trips as we can.",
    localSections: [
      { heading: "Rural lots, sheds, and RVs", body: "Lakeside properties often have real room — multiple outbuildings, sheds, RV pads, and yards that accumulate over the years. That means bigger, sometimes heavier loads than a typical suburban job. We come prepared with the capacity and crew to handle a full shed, a packed garage, or a yard's worth of debris efficiently. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Yard debris, moves, and full clear-outs", body: "We handle yard waste, move-outs, downsizing, and full-property cleanouts across Lakeside. We donate what's reusable through Goodwill and the Salvation Army, recycle what we can, and leave the space swept. On bigger jobs we'll plan the trips so it's done in as few as possible." },
    ],
    faqOverrides: [
      { q: "Do you make the trip out to Lakeside for rural properties?", a: "Yes, regularly — we service Lakeside's larger and semi-rural lots and come prepared for bigger loads. Text photos for a quick quote and we'll plan the right crew and truck." },
      { q: "Can you clear a full shed, garage, and yard?", a: "Yes — bigger loads with sheds and yard debris are common out here. We bring enough capacity to handle it in as few trips as possible. Pricing is volume-based." },
      { q: "How fast can you get to Lakeside?", a: "Often same or next day. Send photos of what needs to go and we'll get you an arrival window." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  {
    slug: "junk-removal-alpine",
    name: "Alpine",
    zips: ["91901"],
    highways: ["I-8"],
    intro: "Alpine is mountain-foothill East County — larger rural and semi-rural lots, homes set back off the road, and the sheds, outbuildings, and yard accumulation that come with property out here. Loads tend to run large, and access can mean a long drive or a private road. We service Alpine on a scheduled basis and come prepared for the bigger jobs.",
    localSections: [
      { heading: "Rural foothill properties", body: "Alpine homes often sit on acreage with detached garages, sheds, barns, and long private drives. The cleanouts run larger and sometimes involve heavier or bulkier items than a suburban job. We come with the truck space and crew to handle it, and we don't mind the drive or the longer carry from a back outbuilding. Flat quote up front, and you only pay for the volume we haul." },
      { heading: "Yard, shed, and full-property clear-outs", body: "We handle yard debris, shed and outbuilding clear-outs, downsizing, and full-property cleanouts across Alpine. We donate what's reusable through Goodwill and the Salvation Army, recycle what we can, and leave the space clean. Because Alpine is a drive out, we'll schedule a time that works and plan the job to be done efficiently." },
    ],
    faqOverrides: [
      { q: "Do you come all the way out to Alpine?", a: "Yes — we service Alpine on a scheduled basis and come prepared for larger rural jobs. Text photos for a quick quote and we'll set a time that works." },
      { q: "Can you clear sheds, outbuildings, and a big yard?", a: "Yes — rural properties with multiple outbuildings and yard accumulation are exactly what we plan for out here. We bring enough capacity to do it in as few trips as possible." },
      { q: "Is there an extra charge for the distance to Alpine?", a: "Pricing is volume-based — what you pay depends on how much we haul. We'll give you a flat quote up front that you approve before we start." },
      { q: "Do you donate or just dump?", a: "We donate everything that still has life through Goodwill, the Salvation Army, and other local charities, and recycle what we can. Only what's genuinely unusable hits the landfill." },
    ],
  },
  { slug: "junk-removal-near-me", name: "San Diego County (Near Me)", neighborhoods: ["All San Diego County zip codes"], landmarks: SD_LANDMARKS.concat(COASTAL_LANDMARKS), highways: ["I-5", "I-8", "I-15", "I-805", "CA-52", "CA-56", "CA-78", "CA-163", "CA-125", "CA-94", "CA-67"], intro: "JunkMD+ services all of San Diego County — coast to mountains, north county to South Bay. Wherever you are, our green truck is nearby." },
];

export const LOCATION_BY_SLUG = Object.fromEntries(
  LOCATIONS.map((l) => [l.slug, l] as const),
);
